//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolMS.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentSubject
    {
        public string Id { get; set; }
        public string SchoolGradeId { get; set; }
        public string SchoolSubjectId { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public System.Guid StudentId { get; set; }
        public bool IsLearning { get; set; }
        public bool IsPrimary { get; set; }
    
        public virtual SchoolGrade SchoolGrade { get; set; }
        public virtual SchoolSubject SchoolSubject { get; set; }
        public virtual Student Student { get; set; }
    }
}
