//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolMS.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.StudentSubjects = new HashSet<StudentSubject>();
            this.TeacherRatings = new HashSet<TeacherRating>();
        }
    
        public System.Guid Id { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string ProfilePhoto { get; set; }
        public int FromCountry { get; set; }
        public int FromState { get; set; }
        public int LivingCountry { get; set; }
        public int LivingState { get; set; }
        public string TimeZone { get; set; }
        public string SchoolName { get; set; }
        public string LookingFor { get; set; }
        public string ShortIntroduction { get; set; }
        public string LongIntroduction { get; set; }
        public string SchoolGrade { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<int> Gender { get; set; }
        public string Skype { get; set; }
        public string Facetime { get; set; }
        public string GoogleHangout { get; set; }
        public string QQ { get; set; }
        public string Webchat { get; set; }
        public string NativeLanguage { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> Isblock { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentSubject> StudentSubjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeacherRating> TeacherRatings { get; set; }
    }
}
