//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolMS.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Teacher()
        {
            this.TeacherCertificates = new HashSet<TeacherCertificate>();
            this.TeacherEducations = new HashSet<TeacherEducation>();
            this.TeacherSubjects = new HashSet<TeacherSubject>();
            this.TeacherExperiences = new HashSet<TeacherExperience>();
            this.TeacherProffessionalCourses = new HashSet<TeacherProffessionalCourse>();
            this.TeacherMaterials = new HashSet<TeacherMaterial>();
            this.TeacherRatings = new HashSet<TeacherRating>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> FromCountry { get; set; }
        public Nullable<int> FromState { get; set; }
        public Nullable<int> LivingCountry { get; set; }
        public Nullable<int> LivingState { get; set; }
        public string TimeZone { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<int> Gender { get; set; }
        public string ShortDescription { get; set; }
        public string LongIntroduction { get; set; }
        public string TeacherSince { get; set; }
        public string UniversityName { get; set; }
        public Nullable<int> YearOfPass { get; set; }
        public string CourseDegreeName { get; set; }
        public string WorkExperienceName { get; set; }
        public string WorkExperienceYear { get; set; }
        public string WorkExperienceDetails { get; set; }
        public string CertificateTitle { get; set; }
        public string CertificatePhoto { get; set; }
        public string CourceTitle { get; set; }
        public string Description { get; set; }
        public string Charges { get; set; }
        public string ViewMoreDetails { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsBlock { get; set; }
        public string ProfilePhoto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeacherCertificate> TeacherCertificates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeacherEducation> TeacherEducations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeacherSubject> TeacherSubjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeacherExperience> TeacherExperiences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeacherProffessionalCourse> TeacherProffessionalCourses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeacherMaterial> TeacherMaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeacherRating> TeacherRatings { get; set; }
    }
}
